### ISSUE TITLE
Fails when the title is changed

### ISSUE THREAD

**Issue by nikaro** [marocchino/checkbox-action#184]
Hello,

It looks like this action doesn't handle the case when only the pull request title is changed.

With this trigger the action can be run when the title or the description is changed:
```yaml
on: 
  pull_request:
    types: [edited]
```

But when only the title is concerned it seems that the `github.context.payload.changes.body` variable (used [here](https://github.com/marocchino/checkbox-action/blob/03a47510e9dcd6931775838d362ec698bac07c16/src/detect.ts)) is empty or absent (cf. [docs](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=edited#pull_request)).

Leading to this error:

```
Run marocchino/checkbox-action@03a47510e9dcd6931775838d362ec698bac07c16
  with:
    action: detect
    error: error
    GITHUB_TOKEN: ***
Error: Cannot read properties of undefined (reading 'from')
```

**Comment by nikaro** [comment]
Hum it looks like it should be fixed on the main branch, by this PR: https://github.com/marocchino/checkbox-action/pull/149

Do you mind doing a new release?

**Comment by marocchino** [comment]
Sorry for late response. I will check this weekend.
